config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get "/index" => "welcome#index"

  get "/home" => "welcome#index", as: :hey

  get "/greeting/:name" => "welcome#greeting"

  get "/hello" => "welcome#hello"

  get "/hello.text" => "welcome#hello"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def greeting
    @name = params[:name]
  end

  def hello
  #  render text: "Hello World"
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreatAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <a href="<%= root_path %>">Home</a>
  <a href="<%= hello_path %>">Hello</a>
  <%= link_to "Hello", hello_path %>
  <hr>
<%= yield %>

</body>
</html>

app/views/welcome/greeting.html.erb
<h1>Hello <%= @name %></h1>

app/views/welcome/hello.html.erb
<h1>Welcome#hello</h1>
<p>Find me in app/views/welcome/hello.html.erb</p>

app/views/welcome/hello.text.erb
Hey there, what's up?

app/views/welcome/index.html.erb
<h1>Welcome to Great Answers</h1>